models/Projects.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "projects".
 *
 * @property int $id
 * @property string $name
 * @property string $logo
 * @property string $description
 * @property string $start_date
 * @property string $end_date
 * @property string $created_at
 * @property int $created_by
 * @property string $updated_at
 * @property int $updated_by
 * @property int $status
 */
class Projects extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'projects';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['name','start_date','description'], 'required'],
            [['start_date', 'end_date', 'created_at', 'updated_at','weekly_call_time','weekly_call_time','web_wireframe_link','web_invision_link','web_test_case_link','app_test_case_link','app_wireframe_link','app_invision_link','web_fs_link','work_day_id','logo'], 'safe'],
            [['created_by', 'updated_by', 'status'], 'integer'],
            [['name'], 'string', 'max' => 50],
            [['logo'], 'string', 'max' => 100],
             ['end_date', 'compareDates'],
        ];
    }
    
      public function compareDates($attribute, $params) 

    {

     $end_date = strtotime($this->end_date);

     $start_date = strtotime($this->start_date);

        if ($end_date < $start_date) {

                $this->addError($attribute, Yii::t('app', ''.$this->end_date.' is not valid '));

        }

    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'logo' => Yii::t('app', 'Logo'),
            'description' => Yii::t('app', 'Description'),
            'start_date' => Yii::t('app', 'Start Date'),
            'end_date' => Yii::t('app', 'End Date'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'status' => Yii::t('app', 'Status'),
        ];
    }
    
	public function getProjectMembers()
    {
      return $this->hasMany(ProjectMembers::className(), ['project_id' => 'id']);
   	}
   	
   	public function getProjectSprints()
   	{
   		return $this->hasMany(ProjectSprints::className(), ['project_id' => 'id']);
   	}
}

controllers/ProjectsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Projects;
use app\models\ProjectsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use yii\base\Model;
use yii\widgets\ActiveForm;
use yii\web\UploadedFile;
  use yii\helpers\Url;
/**
 * ProjectsController implements the CRUD actions for Projects model.
 */
class ProjectsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Projects models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProjectsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Projects model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Projects model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Projects();
        $this->performAjaxValidation($model);
        $path=Url::base(true).'/img/project-icon.jpg';
        if ($model->load(Yii::$app->request->post())) {
              $model->logo = UploadedFile::getInstance($model, 'logo');
               if(!empty($model->logo)){

            $model->logo->saveAs('img/'.'P'.$model->name.'.'.$model->logo->extension);
             $model->logo = Url::base(true).'/img/'.'P'.$model->name.'.'.$model->logo->extension;
          }else{
            $model->logo =Url::base(true).'/img/project-icon.jpg';
          }
            //echo "<pre>"; print_r($model->logo); exit;
            $model->start_date=date('Y-m-d',strtotime($model->start_date)); 
            if(!$model->end_date){
                
            $date = new \DateTime($model->end_date); // Y-m-d
            $date->add(new \DateInterval('P30D')); 
            $model->end_date=  $date->format('Y-m-d');
            }else{
                 $model->end_date=date('Y-m-d',strtotime($model->end_date)); 
            }
           
            $model->save(false);
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'path' => $path,
        ]);
    }

    /**
     * Updates an existing Projects model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->start_date=date('m/d/Y',strtotime($model->start_date)); 
        $model->end_date=date('m/d/Y',strtotime($model->end_date)); 
        $path=$model->logo; 
      
        $this->performAjaxValidation($model);
        if ($model->load(Yii::$app->request->post())) {
       
            $model->logo = UploadedFile::getInstance($model, 'logo');
               if(!empty($model->logo)){

            $model->logo->saveAs('img/'.'P'.$model->name.'.'.$model->logo->extension);
             $model->logo = Url::base(true).'/img/'.'P'.$model->name.'.'.$model->logo->extension;
          }else{
            $model->logo =Url::base(true).'/img/project-icon.jpg';
          }
            $model->start_date=date('Y-m-d',strtotime($model->start_date)); 
             if(!$model->end_date){
                
            $date = new \DateTime($model->end_date); // Y-m-d
            $date->add(new \DateInterval('P30D')); 
            $model->end_date=  $date->format('Y-m-d');
            }else{
                 $model->end_date=date('Y-m-d',strtotime($model->end_date)); 
            }
              $model->save(false);
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
             'path' => $path,
        ]);
    }

    /**
     * Deletes an existing Projects model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Projects model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Projects the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($key)
    {   
        $id=Yii::$app->encryptor->decrypt($key);
        if (($model = Projects::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
          /**
     * Performs ajax validation.
     * @param Model $model
     * @throws \yii\base\ExitException
     */
    protected function performAjaxValidation(Model $model)
    {
        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
           // \Yii::$app->response->format = Response::FORMAT_JSON;
            echo json_encode(ActiveForm::validate($model));
            \Yii::$app->end();
        }
    }
}

views/projects/_form.php
<?php

use yii\helpers\Html;
use app\models\WorkDays;
use app\models\Usertype;
use kartik\widgets\Select2;
use kartik\date\DatePicker;
use kartik\form\ActiveForm;
use kartik\widgets\TimePicker;
use kartik\widgets\FileInput;
/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

     <?php $form = ActiveForm::begin([
      'options' => ['class' => 'form-horiuzontal',
         'enctype' => 'multipart/form-data'
      ],
     'id'      => 'user-form',
     'enableAjaxValidation'   => true,
      'enableClientValidation' => false,
     'fieldConfig' => [
     'template' => "{label}\n<div class=\"col-xs-8\">{input}{hint}{error}</div>",
     'labelOptions' => ['class' => 'col-sm-4 control-label'],
    ],
     ]); ?>
    <div class="row">
        <div class="col-md-12">
             <div class="col-md-6">
 
     <?php echo $form->field($model, 'logo')->widget(FileInput::classname(),[
                  'name' => 'photo',
                   'options'=>[
                    'multiple'=>false,
                    ],
                    'pluginOptions' => [
                      'initialPreview'=>[
                      "".$path."",        
                      ],
                      'browseClass' => 'btn btn-raised btn-primary',
                      'browseIcon' => '<i class="glyphicon glyphicon-camera"></i> ',
                      'browseLabel' =>  'Select ',
                      'removeLabel'=>'Remove',
                      'removeClass' => 'btn btn-raised btn-warning',
                      'showRemove' => false,
                      'showUpload' => false,
                      'removeIcon' => '<i class="glyphicon glyphicon-minus"></i> ',
                      'initialPreviewAsData'=>true,
                      'overwriteInitial'=>true,
                              //'maxFileSize'=>1024
                    ]
                                    ]);//->hint('Recent pic of applicant');
                                  ?>

     <?php 
                    echo $form->field($model, 'start_date')->widget(DatePicker::classname(), [
                      'options' => ['placeholder' => 'Enter Start date ...'],
                      'pluginOptions' => [
                         'startDate'=> '0d',
                         //'format' =>"",
                          'autoclose'=>true
                      ]
                  ]);?>
                   <?php 
                    echo $form->field($model, 'end_date')->widget(DatePicker::classname(), [
                      'options' => ['placeholder' => 'Enter End date ...'],
                      'pluginOptions' => [
                         'startDate'=> '0d',
                         //'format' =>\Yii::$app->formatter->dateFormat,
                          'autoclose'=>true
                      ]
                  ]);?>
   
 
           <?php echo $form->field($model, 'current_index')->widget(Select2::classname(), [
            'data' => [1=>'Yes',0=>'No'],
            'language' => 'en',
              'options' => ['placeholder' => Yii::t('app','Select Index...')],
                'pluginOptions' => [
                 'allowClear' => false
                ],
                //'disabled' => !$model->isNewRecord,
                ]);?>

                    <?php echo $form->field($model, 'work_day_id')->widget(Select2::classname(), [
            'data' =>  WorkDays::getDropDownData(),
            'language' => 'en',
              'options' => ['placeholder' => Yii::t('app','Select Day...')],
                'pluginOptions' => [
                 'allowClear' => false
                ],
                //'disabled' => !$model->isNewRecord,
    ]);?>
    <?= $form->field($model, 'weekly_call_time')->widget(TimePicker::classname(), []);?>
     <?= $form->field($model, 'web_wireframe_link')->textarea(['rows' => 1]) ?>
      
</div>
 <div class="col-md-6">
       <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
      <?= $form->field($model, 'description')->textarea(['rows' => 4]) ?>
      <?= $form->field($model, 'owner')->textInput(['maxlength' => true]) ?>
      <?= $form->field($model, 'platform')->textInput(['maxlength' => true]) ?>
      <?= $form->field($model, 'app_test_case_link')->textarea(['rows' => 1]) ?>
      <?= $form->field($model, 'app_wireframe_link')->textarea(['rows' => 1]) ?>
      <?= $form->field($model, 'app_invision_link')->textarea(['rows' => 1]) ?>
      <?= $form->field($model, 'web_fs_link')->textarea(['rows' => 1]) ?>
      <?= $form->field($model, 'web_invision_link')->textarea(['rows' => 1]) ?>
        <?= $form->field($model, 'web_test_case_link')->textarea(['rows' =>1]) ?>
    
     


</div>
</div>
 
</div>
</div>
  <div class="form-group btn-group">
         <?= Html::submitButton($model->isNewRecord ? Yii::t('app', '<i class="ace-icon fa fa-plus"> Save</i>') : Yii::t('app', '<i class="ace-icon fa fa-pencil"> Update</i>'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>

         <?= Html::a('<i class="ace-icon fa fa-remove"> Cancel</i>', ['projects/index'], ['class'=>'btn btn-danger']); ?>
         <?php if($model->isNewRecord): ?>
         
         <button type="reset" class="btn btn-info">
                        <i class="ace-icon fa fa-undo bigger-110"></i>
                        Reset
         </button>
         <?php endif ?>
      </div>
   

    <?php ActiveForm::end(); ?>

</div>

views/projects/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProjectsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="projects-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'logo') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'start_date') ?>

    <?php // echo $form->field($model, 'end_date') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/projects/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = Yii::t('app', 'Create Projects');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="projects-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
         'path' => $path,
    ]) ?>

</div>

views/projects/index.php
<?php
use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use kartik\widgets\Select2;
use app\models\Usertype;



/* @var $this yii\web\View */
/* @var $searchModel app\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Projects');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <?php Pjax::begin(); ?>    

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],

            'name',
            'logo',
            'description:ntext',
            
            [
             'attribute'=>'start_date',
               'value' => function($model, $key, $index, $column) {
                    return date('m/d/Y',strtotime($model->start_date));
                }
            ],  
            'weekly_call_time',
            'web_wireframe_link',
            'web_invision_link',
            'web_test_case_link',
            'app_test_case_link',
            'app_wireframe_link',
            'app_invision_link',
            'web_fs_link',
          
           

            ['class' => '\kartik\grid\ActionColumn',
                                        
                  'template' => '{update}&nbsp{view}&nbsp{map}',
                    'buttons' => [
                    'map' => function ($url, $model) {
                                  return Html::a('Member', $url, [
                                    'title' => Yii::t('app', 'Map Members'),'class'=>'btn btn-xs btn-primary','target'=>'_blank'
                                 ]);
                              }, 
                  ],

                    'urlCreator' => function ($action, $model, $url, $index) {
                         $hash=Yii::$app->encryptor->encrypt($model->id); 
                         if ($action === 'view') {
                            return Url::to(['projects/view','id'=>$hash]);
                         }else if($action === 'update'){
                          return Url::to(['projects/update','id'=>$hash]);
                         }else if($action === 'delete'){
                          return Url::to(['projects/delete','id'=>$hash]);
                         }else if($action === 'map'){
                          return Url::to(['project-members/create','id'=>Yii::$app->encryptor->encrypt($model->id)]);
                         }
                    },
            ],

        ],

         'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="white fa fa-users "></i>Projects</h3>',
            'type'=>'primary',
             'before'=>Html::a(Yii::t('app', '<i class="glyphicon glyphicon-plus"></i> Create {modelClass}', ['modelClass' => 'Projects',]), ['create'], ['class' => 'btn btn-primary']) ,
            'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset Search', ['index'], ['class' => 'btn btn-info']),
            'showFooter'=>true,
            'pager'=>false
          ],
            'toolbar' => [
              //'{export}'
              ],
            'exportConfig' => [
            GridView::HTML =>[],
            //  GridView::PDF =>[],
            GridView::TEXT => [],
            GridView::EXCEL => [],
            ]
    ]); ?>

<?php Pjax::end(); ?>
  
</div>

views/projects/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = Yii::t('app', 'Update Projects: {name}', [
    'name' => $model->name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => Yii::$app->encryptor->encrypt($model->id)]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="projects-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
         'path' => $path,
    ]) ?>

</div>

views/projects/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Projects */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Projects'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="projects-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' =>Yii::$app->encryptor->encrypt($model->id)], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' =>Yii::$app->encryptor->encrypt($model->id)], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [

            'name',
            'logo',
            'description:ntext',
             [
             'attribute'=>'start_date',
               'value' => function($model) {
                    return date('m/d/Y',strtotime($model->start_date));
                }
            ],
             [
             'attribute'=>'end_date',
               'value' => function($model) {
                    return date('m/d/Y',strtotime($model->end_date));
                }
            ],
                'weekly_call_time',
            'web_wireframe_link',
            'web_invision_link',
            'web_test_case_link',
            'app_test_case_link',
            'app_wireframe_link',
            'app_invision_link',
            'web_fs_link',
         
        ],
    ]) ?>

</div>